
import __ASTRO_IMAGE_IMPORT_ZXXUWQ from "../../assets/imagens/projetos/geladeira.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojetos%2F06-innovation-and-patent-pipeline.md";
import __ASTRO_IMAGE_IMPORT_27lTYG from "../../assets/imagens/projetos/geladeira.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojetos%2Fdraft.md";
import __ASTRO_IMAGE_IMPORT_117pJs from "../../assets/imagens/projetos/imagem-grid-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojetos%2F01-product-launch-governance.md";
import __ASTRO_IMAGE_IMPORT_12LNfH from "../../assets/imagens/projetos/imagem-grid-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojetos%2F02-portfolio-roadmap-execution.md";
import __ASTRO_IMAGE_IMPORT_Z1BeFpz from "../../assets/imagens/projetos/imagem-grid-3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojetos%2F03-materials-engineering-programs.md";
import __ASTRO_IMAGE_IMPORT_ZGT1PK from "../../assets/imagens/projetos/imagem-grid-4.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojetos%2F04-cost-and-pmo-initiatives.md";
import __ASTRO_IMAGE_IMPORT_1QiAtf from "../../assets/imagens/projetos/imagem-grid-5.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojetos%2F05-multicultural-delivery.md";
import __ASTRO_IMAGE_IMPORT_Z2wOruU from "../../assets/imagens/projetos/imagem-grid-6.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojetos%2F06-new-product-development.md";
export default new Map([["../../assets/imagens/projetos/geladeira.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojetos%2F06-innovation-and-patent-pipeline.md", __ASTRO_IMAGE_IMPORT_ZXXUWQ], ["../../assets/imagens/projetos/geladeira.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojetos%2Fdraft.md", __ASTRO_IMAGE_IMPORT_27lTYG], ["../../assets/imagens/projetos/imagem-grid-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojetos%2F01-product-launch-governance.md", __ASTRO_IMAGE_IMPORT_117pJs], ["../../assets/imagens/projetos/imagem-grid-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojetos%2F02-portfolio-roadmap-execution.md", __ASTRO_IMAGE_IMPORT_12LNfH], ["../../assets/imagens/projetos/imagem-grid-3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojetos%2F03-materials-engineering-programs.md", __ASTRO_IMAGE_IMPORT_Z1BeFpz], ["../../assets/imagens/projetos/imagem-grid-4.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojetos%2F04-cost-and-pmo-initiatives.md", __ASTRO_IMAGE_IMPORT_ZGT1PK], ["../../assets/imagens/projetos/imagem-grid-5.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojetos%2F05-multicultural-delivery.md", __ASTRO_IMAGE_IMPORT_1QiAtf], ["../../assets/imagens/projetos/imagem-grid-6.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojetos%2F06-new-product-development.md", __ASTRO_IMAGE_IMPORT_Z2wOruU]]);
		