
import __ASTRO_IMAGE_IMPORT_kNb5 from "../../assets/imagens/projetos/ar.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojetos%2F03-materials-engineering-programs.md";
import __ASTRO_IMAGE_IMPORT_Z2fIO4K from "../../assets/imagens/projetos/ar.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojetos%2F05-multicultural-delivery.md";
import __ASTRO_IMAGE_IMPORT_Z27CgNX from "../../assets/imagens/projetos/brastemp.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojetos%2F02-portfolio-roadmap-execution.md";
import __ASTRO_IMAGE_IMPORT_f8fxg from "../../assets/imagens/projetos/brastemp.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojetos%2F04-cost-and-pmo-initiatives.md";
import __ASTRO_IMAGE_IMPORT_1uWlxh from "../../assets/imagens/projetos/geladeira.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojetos%2F01-product-launch-governance.md";
import __ASTRO_IMAGE_IMPORT_ZXXUWQ from "../../assets/imagens/projetos/geladeira.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojetos%2F06-innovation-and-patent-pipeline.md";
import __ASTRO_IMAGE_IMPORT_2k2HGA from "../../assets/imagens/projetos/geladeira.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojetos%2F06-new-product-development.md";
import __ASTRO_IMAGE_IMPORT_27lTYG from "../../assets/imagens/projetos/geladeira.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojetos%2Fdraft.md";
export default new Map([["../../assets/imagens/projetos/ar.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojetos%2F03-materials-engineering-programs.md", __ASTRO_IMAGE_IMPORT_kNb5], ["../../assets/imagens/projetos/ar.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojetos%2F05-multicultural-delivery.md", __ASTRO_IMAGE_IMPORT_Z2fIO4K], ["../../assets/imagens/projetos/brastemp.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojetos%2F02-portfolio-roadmap-execution.md", __ASTRO_IMAGE_IMPORT_Z27CgNX], ["../../assets/imagens/projetos/brastemp.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojetos%2F04-cost-and-pmo-initiatives.md", __ASTRO_IMAGE_IMPORT_f8fxg], ["../../assets/imagens/projetos/geladeira.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojetos%2F01-product-launch-governance.md", __ASTRO_IMAGE_IMPORT_1uWlxh], ["../../assets/imagens/projetos/geladeira.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojetos%2F06-innovation-and-patent-pipeline.md", __ASTRO_IMAGE_IMPORT_ZXXUWQ], ["../../assets/imagens/projetos/geladeira.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojetos%2F06-new-product-development.md", __ASTRO_IMAGE_IMPORT_2k2HGA], ["../../assets/imagens/projetos/geladeira.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojetos%2Fdraft.md", __ASTRO_IMAGE_IMPORT_27lTYG]]);
		